2023-05-09 16:27:24,341 p=78945 u=ubuntu n=ansible | node002.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: root@192.168.191.141: Permission denied (publickey,password).",
    "unreachable": true
}
2023-05-09 16:27:24,375 p=78945 u=ubuntu n=ansible | node003.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: root@192.168.191.142: Permission denied (publickey,password).",
    "unreachable": true
}
2023-05-09 16:27:27,303 p=78945 u=ubuntu n=ansible | node001.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.140 port 22: No route to host",
    "unreachable": true
}
2023-05-09 16:28:19,985 p=79443 u=ubuntu n=ansible | Using /home/ubuntu/ansible-exercise/scenario-1/ansible.cfg as config file
2023-05-09 16:28:20,249 p=79443 u=ubuntu n=ansible | node003.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: root@192.168.191.142: Permission denied (publickey,password).",
    "unreachable": true
}
2023-05-09 16:28:20,249 p=79443 u=ubuntu n=ansible | node002.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: root@192.168.191.141: Permission denied (publickey,password).",
    "unreachable": true
}
2023-05-09 16:28:23,253 p=79443 u=ubuntu n=ansible | node001.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.140 port 22: No route to host",
    "unreachable": true
}
2023-05-09 16:30:55,114 p=80154 u=ubuntu n=ansible | Using /home/ubuntu/ansible-exercise/scenario-1/ansible.cfg as config file
2023-05-09 16:30:55,332 p=80154 u=ubuntu n=ansible | node002 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: root@node002: Permission denied (publickey,password).",
    "unreachable": true
}
2023-05-09 16:30:55,333 p=80154 u=ubuntu n=ansible | node003 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: root@node003: Permission denied (publickey,password).",
    "unreachable": true
}
2023-05-09 16:30:58,284 p=80154 u=ubuntu n=ansible | node001 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host node001 port 22: No route to host",
    "unreachable": true
}
2023-05-09 16:31:26,525 p=80321 u=ubuntu n=ansible | Using /home/ubuntu/ansible-exercise/scenario-1/ansible.cfg as config file
2023-05-09 16:31:28,392 p=80321 u=ubuntu n=ansible | node003 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2023-05-09 16:31:28,450 p=80321 u=ubuntu n=ansible | node002 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2023-05-09 16:31:29,707 p=80321 u=ubuntu n=ansible | node001 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host node001 port 22: No route to host",
    "unreachable": true
}
2023-05-09 16:31:50,360 p=80511 u=ubuntu n=ansible | Using /home/ubuntu/ansible-exercise/scenario-1/ansible.cfg as config file
2023-05-09 16:31:51,182 p=80511 u=ubuntu n=ansible | node002.b9cluster.local | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2023-05-09 16:31:51,200 p=80511 u=ubuntu n=ansible | node003.b9cluster.local | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2023-05-09 16:31:53,539 p=80511 u=ubuntu n=ansible | node001.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.140 port 22: No route to host",
    "unreachable": true
}
2023-05-09 16:32:06,480 p=80680 u=ubuntu n=ansible | Using /home/ubuntu/ansible-exercise/scenario-1/ansible.cfg as config file
2023-05-09 16:32:07,119 p=80680 u=ubuntu n=ansible | node003.b9cluster.local | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2023-05-09 16:32:07,146 p=80680 u=ubuntu n=ansible | node002.b9cluster.local | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2023-05-09 16:32:09,674 p=80680 u=ubuntu n=ansible | node001.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.140 port 22: No route to host",
    "unreachable": true
}
2023-05-09 16:33:03,557 p=81061 u=ubuntu n=ansible | node002.b9cluster.local | FAILED | rc=2 >>
grep: /etc/iso-release: No such file or directorynon-zero return code

2023-05-09 16:33:03,558 p=81061 u=ubuntu n=ansible | node003.b9cluster.local | FAILED | rc=2 >>
grep: /etc/iso-release: No such file or directorynon-zero return code

2023-05-09 16:33:06,188 p=81061 u=ubuntu n=ansible | node001.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.140 port 22: No route to host",
    "unreachable": true
}
2023-05-09 16:33:35,410 p=81251 u=ubuntu n=ansible | node002.b9cluster.local | CHANGED | rc=0 >>
NAME="Ubuntu"

2023-05-09 16:33:35,420 p=81251 u=ubuntu n=ansible | node003.b9cluster.local | CHANGED | rc=0 >>
NAME="Ubuntu"

2023-05-09 16:33:38,069 p=81251 u=ubuntu n=ansible | node001.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.140 port 22: No route to host",
    "unreachable": true
}
2023-05-21 10:11:23,125 p=18679 u=ubuntu n=ansible | node001.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.140 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:11:23,134 p=18679 u=ubuntu n=ansible | node003.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.142 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:11:23,135 p=18679 u=ubuntu n=ansible | node002.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.141 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:12:31,652 p=19011 u=ubuntu n=ansible | [WARNING]: Found both group and host with same name: workstation

2023-05-21 10:12:31,988 p=19011 u=ubuntu n=ansible | workstation | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added '172.16.189.245' (ED25519) to the list of known hosts.\r\nubuntu@172.16.189.245: Permission denied (publickey,password).",
    "unreachable": true
}
2023-05-21 10:12:41,763 p=19011 u=ubuntu n=ansible | node001.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.140 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:12:41,779 p=19011 u=ubuntu n=ansible | node003.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.142 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:12:41,790 p=19011 u=ubuntu n=ansible | node002.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.141 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:14:16,568 p=19424 u=ubuntu n=ansible | node001.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.140 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:14:16,573 p=19424 u=ubuntu n=ansible | node002.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.141 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:14:16,587 p=19424 u=ubuntu n=ansible | node003.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.142 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:25:18,005 p=21284 u=ubuntu n=ansible | worker2 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ubuntu@172.16.189.192: Permission denied (publickey,password).",
    "unreachable": true
}
2023-05-21 10:25:27,901 p=21284 u=ubuntu n=ansible | node001.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.140 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:25:27,904 p=21284 u=ubuntu n=ansible | node002.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.141 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:25:27,916 p=21284 u=ubuntu n=ansible | node003.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.142 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:26:05,244 p=21509 u=ubuntu n=ansible | openstack | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ubuntu@172.16.189.192: Permission denied (publickey,password).",
    "unreachable": true
}
2023-05-21 10:26:15,138 p=21509 u=ubuntu n=ansible | node001.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.140 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:26:15,152 p=21509 u=ubuntu n=ansible | node002.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.141 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:26:15,157 p=21509 u=ubuntu n=ansible | node003.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.142 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:28:47,509 p=22074 u=ubuntu n=ansible | openstack | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ubuntu@172.16.189.192: Permission denied (publickey,password).",
    "unreachable": true
}
2023-05-21 10:28:56,533 p=22074 u=ubuntu n=ansible |  [ERROR]: User interrupted execution

2023-05-21 10:29:10,872 p=22245 u=ubuntu n=ansible | openstack | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ubuntu@172.16.189.192: Permission denied (publickey,password).",
    "unreachable": true
}
2023-05-21 10:29:20,748 p=22245 u=ubuntu n=ansible | node001.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.140 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:29:20,766 p=22245 u=ubuntu n=ansible | node002.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.141 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:29:20,774 p=22245 u=ubuntu n=ansible | node003.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.142 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:31:18,789 p=22754 u=ubuntu n=ansible | Using /home/ubuntu/ansible-exercise/scenario-1/ansible.cfg as config file
2023-05-21 10:31:19,084 p=22754 u=ubuntu n=ansible | openstack | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ubuntu@172.16.189.192: Permission denied (publickey,password).",
    "unreachable": true
}
2023-05-21 10:31:28,918 p=22754 u=ubuntu n=ansible | node001.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.140 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:31:29,124 p=22754 u=ubuntu n=ansible | node002.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.141 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:31:29,212 p=22754 u=ubuntu n=ansible | node003.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.142 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:34:55,209 p=23459 u=ubuntu n=ansible | Using /home/ubuntu/ansible-exercise/scenario-1/ansible.cfg as config file
2023-05-21 10:34:55,553 p=23459 u=ubuntu n=ansible | openstack | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ubuntu@172.16.189.192: Permission denied (publickey,password).",
    "unreachable": true
}
2023-05-21 10:35:05,424 p=23459 u=ubuntu n=ansible | node001.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.140 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:35:05,533 p=23459 u=ubuntu n=ansible | node002.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.141 port 22: Connection timed out",
    "unreachable": true
}
2023-05-21 10:35:05,572 p=23459 u=ubuntu n=ansible | node003.b9cluster.local | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.191.142 port 22: Connection timed out",
    "unreachable": true
}
